import like from '../../assets/like.svg';
import Check_round_on from '../../assets/Check_round_on.svg';
import selfproject_floating_btn from '../../assets/selfproject_floating_btn.svg';
import minus_dis from '../../assets/minus_()_dis.svg';
import Check_ from '../../assets/Check_.svg';
import plus_s from '../../assets/plus_s.svg';
import close_recent_search from '../../assets/close_recent search.svg';
import Check from '../../assets/Check.svg';
import new_projectfile from '../../assets/new projectfile.svg';
import close from '../../assets/close.svg';
import reload from '../../assets/reload.svg';
import back_w from '../../assets/back_w.svg';
import projectfile_w from '../../assets/projectfile_w.svg';
import more_with_typo from '../../assets/more_with_typo.svg';
import back_B from '../../assets/back_B.svg';
import projectfile_B from '../../assets/projectfile_B.svg';
import like_s_ from '../../assets/like_s_.svg';
import More from '../../assets/more.svg';
import like_ from '../../assets/like_.svg';
import Top_floating_btn from '../../assets/Top_floating_btn.svg';
import Check_round_off from '../../assets/Check_round_off.svg';
import minus_s from '../../assets/minus_s.svg';
import like_s from '../../assets/like_s.svg';
import plus_dis from '../../assets/plus_dis.svg';
import plus_ from '../../assets/plus_.svg';
import more_s from '../../assets/more_s.svg';
import minus_ from '../../assets/minus_().svg';
import black_searchBar from '../../assets/검색바/back_검색바 용.svg';
import close_searchBar from '../../assets/검색바/close_검색바 용.svg';
import items_hidden from '../../assets/구성품 더보기,간략히/hidden.svg';
import items_more from '../../assets/구성품 더보기,간략히/more.svg';
import plan_minus from '../../assets/기획서 리스트 편집용/minus_.svg';
import plan_new_ptroject from '../../assets/기획서 리스트 편집용/new projectfile.svg';
import Check_off from '../../assets/직접기획/Check_off.svg';
import Check_on from '../../assets/직접기획/Check_on.svg';
import view_more from '../../assets/직접기획/view_more.svg';

export const like = props => <like {...props} />;
export const Check_round_on = props => <Check_round_on {...props} />;
export const selfproject_floating_btn = props => (
  <selfproject_floating_btn {...props} />
);
export const minus_dis = props => <minus_dis {...props} />;
export const Check_ = props => <Check_ {...props} />;
export const plus_s = props => <plus_s {...props} />;
export const close_recent_search = props => <close_recent_search {...props} />;
export const Check = props => <Check {...props} />;
export const new_projectfile = props => <new_projectfile {...props} />;
export const close = props => <close {...props} />;
export const reload = props => <reload {...props} />;
export const back_w = props => <back_w {...props} />;
export const projectfile_w = props => <projectfile_w {...props} />;
export const more_with_typo = props => <more_with_typo {...props} />;
export const back_B = props => <back_B {...props} />;
export const projectfile_B = props => <projectfile_B {...props} />;
export const like_s_ = props => <like_s_ {...props} />;
export const More = props => <More {...props} />;
export const like_ = props => <like_ {...props} />;
export const Top_floating_btn = props => <Top_floating_btn {...props} />;
export const Check_round_off = props => <Check_round_off {...props} />;
export const minus_s = props => <minus_s {...props} />;
export const like_s = props => <like_s {...props} />;
export const plus_dis = props => <plus_dis {...props} />;
export const plus_ = props => <plus_ {...props} />;
export const more_s = props => <more_s {...props} />;
export const minus_ = props => <minus_ {...props} />;
export const black_searchBar = props => <black_searchBar {...props} />;
export const close_searchBar = props => <close_searchBar {...props} />;
export const items_hidden = props => <items_hidden {...props} />;
export const items_more = props => <items_more {...props} />;
export const plan_minus = props => <plan_minus {...props} />;
export const plan_new_ptroject = props => <plan_new_ptroject {...props} />;
export const Check_off = props => <Check_off {...props} />;
export const Check_on = props => <Check_on {...props} />;
export const view_more = props => <view_more {...props} />;
